### PR TITLE
Fix issue with packable values

### PR DESCRIPTION
**Pull request by alanpoulain**

### CODE REVIEW

**Comment by bramp** [comment]
Looks good, but I haven't touched this code in some time. Can you tell me
the difference between packed and packable?

Thanks

**Comment by alanpoulain** [comment]
A packable value is a value which can be packed but is not (for example a repeated int32).
See there: https://developers.google.com/protocol-buffers/docs/proto3#specifying-field-rules

**Comment by bramp** [comment]
I'm going to take your word that this change is appropriate.

But what confuses me from quickly reading up on this, is how did any repeatable field in the past work? Surely they are all packable, but the code previously could handle repeated ints. Did the definition of packable() perhaps change between proto2 and proto3?

Either way, accepted, and we can revert if it causes problems for people.

**Comment by alanpoulain** [comment]
Maybe repeated int32 was not packable before?
This link could help:
https://developers.google.com/protocol-buffers/docs/encoding#packed-repeated-fields

**Pull request merged**
